// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2rPMJppepzSY_Vs-qiwpcZyWlTwc5iJE',
    appId: '1:969631501948:web:6884eba80211085a4343f9',
    messagingSenderId: '969631501948',
    projectId: 'edgf-378313',
    authDomain: 'edgf-378313.firebaseapp.com',
    storageBucket: 'edgf-378313.appspot.com',
    measurementId: 'G-3NG2P5P9SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABK4xVp39_JsS1U574j4gkxSvdF6xwpJI',
    appId: '1:969631501948:android:26950ff02e2020674343f9',
    messagingSenderId: '969631501948',
    projectId: 'edgf-378313',
    storageBucket: 'edgf-378313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxL19g7kvrtqnG79YuxD-3gaUQyah5I_A',
    appId: '1:969631501948:ios:9f226587d1a410b34343f9',
    messagingSenderId: '969631501948',
    projectId: 'edgf-378313',
    storageBucket: 'edgf-378313.appspot.com',
    iosBundleId: 'com.kuchen.morgan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxL19g7kvrtqnG79YuxD-3gaUQyah5I_A',
    appId: '1:969631501948:ios:af678dde8e1620cc4343f9',
    messagingSenderId: '969631501948',
    projectId: 'edgf-378313',
    storageBucket: 'edgf-378313.appspot.com',
    iosBundleId: 'com.kuchen.morgan.RunnerTests',
  );
}
